export PATCHFOX_DATASOURCE=NA
export PATCHFOX_API_TOKEN=NA
export PATCHFOX_PATH_TO_SYFT=**PUT PATH TO SYFT HERE**
export PATCHFOX_ORGANIZATION=**PUT NAME FOR DATASET HERE -- THIS IS THE NAME FOR THE COLLECTION OF DATA YOU ARE UPLOADING** 
export GITHUB_TOKEN=NA
